spring:
  application:
    name: fruit
  datasource:
    url: jdbc:mysql://localhost:3306/fruit_store?useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
        enable_lazy_load_no_trans: true
        format_sql: create
    show-sql: true

jwt:
  secret: keysecret2021

server:
  error:
    include-message: always
  port: 8080
